### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by jj10133** [pushpalroy/JetTaskKMM#10]
### Actual behaviour
So I just cloned the project and tried to build in Android Studio however throws an error 

### Expected behaviour
Should compile the desktop side of app

### I'm seeing this behaviour on
![image](https://github.com/pushpalroy/JetTaskBoardKMP/assets/35785259/0580f544-4cd6-462c-bf42-838e26863f06)

#### Hardware models
Asus UX303UB

#### OS versions
Linux Fedora 38

### So how can we reproduce this?
1. Just clone
2. Try to build in Android Studio

**Comment by jj10133** [comment]
Is that we need to define some compile option for desktop side, like I don't anything about compose multiplatform

**Comment by jj10133** [comment]
Currently using open-jdk-17 so I think this could be an issue, or using jetbrain runtime can resolve this. I also had a look at the template so yeah it's should work

**Comment by pushpalroy** [comment]
@nishp77 Looking into it. Will keep you updated.

**Comment by pushpalroy** [comment]
Looks like a JDK issue in the system where the project was built.
